on:
  workflow_dispatch:
permissions: write-all
jobs:
  setup-cloudflare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: |
          npm install
          npm run build
      - run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Action Commit"
          git push
